services:
    dynamodb-local:
        command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
        image: "amazon/dynamodb-local:latest"
        container_name: dynamodb-local
        ports:
            - "8000:8000"
        volumes:
            - "./docker/dynamodb:/home/dynamodblocal/data"
        working_dir: /home/dynamodblocal
    
    # broserv
    # dynamodb-local:
    #     command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
    #     image: "amazon/dynamodb-local:latest"
    #     container_name: dynamodb-local
    #     ports:
    #         - "8009:8000"
    #     volumes:
    #         - "./LocalPackagingTools/dynamodb:/home/dynamodblocal/data"
    #     working_dir: /home/dynamodblocal
    #     restart: always
    #     user: root
    #     networks:
    #         - dynamo
    # dynamodb-admin:
    #     environment:
    #         - DYNAMO_ENDPOINT=http://dynamodb-local:8000
    #     depends_on:
    #         - dynamodb-local
    #     image: aaronshaf/dynamodb-admin:latest
    #     container_name: dynamodb-admin
    #     restart: always
    #     ports:
    #         - "8008:8001"
    #     networks:
    #         - dynamo